---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: naw-alert
  namespace: flux-system
spec:
  eventSources:
  - kind: GitRepository
    name: my-repo
  - kind: Kustomization
    name: my-kustomization
  providerRef:
    name: naw-provider
